In [56]:
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances, pairwise_distances
import io
import numpy as np


x = [(1, 3, -5, 7)]
x_ = [(2, -4, 0, 8)]

In [45]:
euclidean_distances(x, x_)

array([[8.71779789]])

In [46]:
manhattan_distances(x, x_)

array([[14.]])

In [47]:
pairwise_distances(x, x_, metric='chebyshev')

array([[7.]])

In [48]:
data = '''id,X,Y,Class
1,28,10,1
2,49,49,1
3,48,35,0
4,36,33,1
5,45,54,0'''

data = pd.read_csv(io.StringIO(data), index_col='id')
data

X   Y  Class
id               
1   28  10      1
2   49  49      1
3   48  35      0
4   36  33      1
5   45  54      0

In [49]:
df = list(zip(data.X, data.Y))
df

[(28, 10), (49, 49), (48, 35), (36, 33), (45, 54)]

In [50]:
euclidean_distances(df, [(33, 47)])

array([[37.33630941],
       [16.1245155 ],
       [19.20937271],
       [14.31782106],
       [13.89244399]])

In [51]:
manhattan_distances(df, [(33, 47)])

array([[42.],
       [18.],
       [27.],
       [17.],
       [19.]])

In [52]:
pairwise_distances(df, [(33, 47)], metric='chebyshev')

array([[37.],
       [16.],
       [15.],
       [14.],
       [12.]])

In [61]:
class_0 = data[data.Class == 0]
class_0 = list(zip(class_0.X, class_0.Y)) 

In [62]:
w_sum_0 = sum(1 / (euclidean_distances(class_0, [(33, 47)])) ** 2)
np.round(w_sum_0, 3)

array([0.008])

In [63]:
class_1 = data[data.Class == 1]
class_1 = list(zip(class_1.X, class_1.Y)) 

In [66]:
w_sum_1 = sum(1 / (euclidean_distances(class_1, [(33, 47)])) ** 2)
np.round(w_sum_1, 4)

array([0.0094])